name: 🔒 Security Vulnerability
description: Report a security vulnerability (private disclosure)
title: "[Security] "
labels: ["security", "critical"]
assignees: ["security-team"]

body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ SECURITY VULNERABILITY REPORT ⚠️
        
        **IMPORTANT**: If this is a critical security vulnerability that could be exploited, 
        please consider reporting it privately instead of creating a public issue.
        
        📧 **Private Disclosure**: Send details to security@[your-domain].com
        
        For less critical security improvements or public vulnerabilities in dependencies, 
        you can use this public template.

  - type: checkboxes
    id: disclosure
    attributes:
      label: Disclosure Type
      options:
        - label: This is a low-risk security improvement (public disclosure OK)
          required: false
        - label: This is about a publicly known vulnerability in dependencies
          required: false
        - label: I have already contacted the security team privately
          required: false
        - label: This should remain private until fixed (STOP - use private email instead)
          required: false

  - type: textarea
    id: summary
    attributes:
      label: Vulnerability Summary
      description: Brief description of the security issue
      placeholder: Describe the vulnerability without revealing exploitation details
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How severe do you consider this vulnerability?
      options:
        - Critical - Immediate threat, active exploitation possible
        - High - Significant risk, requires urgent attention
        - Medium - Moderate risk, should be addressed soon
        - Low - Minor risk, can be addressed in regular cycle
        - Info - Security improvement suggestion
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - Code Injection
        - Cross-Site Scripting (XSS)
        - SQL Injection
        - Path Traversal
        - Information Disclosure
        - Cryptographic Issues
        - Dependency Vulnerability
        - Configuration Security
        - Access Control
        - Other
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - Component: version range
        - Files/modules affected
        - Specific functions or endpoints
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve? (avoid specific exploitation steps)
      placeholder: |
        Describe the potential impact without providing a step-by-step exploit:
        - Data that could be accessed
        - Systems that could be compromised
        - Business impact
    validations:
      required: true

  - type: textarea
    id: conditions
    attributes:
      label: Attack Prerequisites
      description: What conditions are needed for this vulnerability to be exploitable?
      placeholder: |
        - Authentication required?
        - Network access requirements
        - Specific configuration needed
        - Other preconditions

  - type: input
    id: versions
    attributes:
      label: Affected Versions
      description: Which versions are vulnerable?
      placeholder: "e.g., all versions, >= v1.0.0, v1.2.0 - v1.5.0"
    validations:
      required: true

  - type: textarea
    id: discovery
    attributes:
      label: Discovery Method
      description: How was this vulnerability discovered?
      placeholder: |
        - Security scan/tool used
        - Manual code review
        - Incident response
        - Researcher report
        - Automated testing

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this issue?
      placeholder: |
        - Immediate workarounds
        - Suggested code changes (general approach)
        - Configuration recommendations
        - Additional security measures

  - type: textarea
    id: references
    attributes:
      label: References
      description: Relevant security references, CVEs, or documentation
      placeholder: |
        - CVE numbers
        - Security advisories
        - OWASP references
        - Research papers

  - type: checkboxes
    id: testing
    attributes:
      label: Testing
      options:
        - label: I have a proof-of-concept (will share privately)
          required: false
        - label: I have tested this on the latest version
          required: false
        - label: I have tested potential fixes
          required: false

  - type: textarea
    id: timeline
    attributes:
      label: Disclosure Timeline
      description: Any timeline considerations?
      placeholder: |
        - When did you discover this?
        - Any external deadlines?
        - Coordinated disclosure preferences

  - type: checkboxes
    id: agreement
    attributes:
      label: Responsible Disclosure Agreement
      options:
        - label: I will not publicly disclose details until a fix is available
          required: true
        - label: I will not actively exploit this vulnerability
          required: true
        - label: I understand this report may be shared with relevant maintainers
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **After submitting**: If this is a critical issue, please also email security@[your-domain].com 
        with a link to this issue for immediate attention.
        
        Thank you for helping keep dev-agents secure! 🛡️